name: Azure Web App Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: kidzaimathapp30237       # <-- your web app name
  NODE_VERSION: '20.x'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # --- Install root dependencies
      - name: Install root deps
        run: npm ci

      # --- Build client with the Stripe publishable key
      - name: Build client (Vite)
        env:
          # This must be present at build time; value comes from GitHub Secrets
          VITE_STRIPE_PUBLIC_KEY: ${{ secrets.VITE_STRIPE_PUBLIC_KEY }}
        run: |
          # Optional: fail fast if secret is empty
          if [ -z "${VITE_STRIPE_PUBLIC_KEY}" ]; then
            echo "VITE_STRIPE_PUBLIC_KEY is empty. Add it as a GitHub Actions secret."
            exit 1
          fi
          npm run build
          # Vite outputs to dist/public (per your logs)

      # --- Compile server TypeScript to server-build/
      - name: Compile server TypeScript
        run: |
          npm run build:server
          # Ensure the server-build/public contains the client build
          rsync -a --delete dist/public/ server-build/public/

      # --- Install production deps in server-build/
      - name: Install production deps inside server-build
        run: |
          # Copy the root package.json (or your server package.json if you keep a separate one)
          cp package.json server-build/
          npm ci --omit=dev --prefix server-build

      # --- Create a deployment package
      - name: Create deployment package
        run: |
          cd server-build
          zip -r ../server-build.zip .

      # --- Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: server-build.zip
